// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhpnZDYQjaO_TrxErzZRJK3RkYEJrSJ0',
    appId: '1:216483381190:web:76429ae9e8f932ad9a3cc7',
    messagingSenderId: '216483381190',
    projectId: 'pos-nlh',
    authDomain: 'pos-nlh.firebaseapp.com',
    storageBucket: 'pos-nlh.firebasestorage.app',
    measurementId: 'G-R485VR3YDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PJ0yyeXzX2xZrBMfW9z0oN7etQyzL7k',
    appId: '1:216483381190:android:7901f621c03cc39b9a3cc7',
    messagingSenderId: '216483381190',
    projectId: 'pos-nlh',
    storageBucket: 'pos-nlh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZN6CM-Yifgxjut0RlOHLW9hFgDFFKro',
    appId: '1:216483381190:ios:f552af556b5bd5e89a3cc7',
    messagingSenderId: '216483381190',
    projectId: 'pos-nlh',
    storageBucket: 'pos-nlh.firebasestorage.app',
    iosBundleId: 'com.naylinhtet.posnlh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZN6CM-Yifgxjut0RlOHLW9hFgDFFKro',
    appId: '1:216483381190:ios:445f6a84f44c4d7d9a3cc7',
    messagingSenderId: '216483381190',
    projectId: 'pos-nlh',
    storageBucket: 'pos-nlh.firebasestorage.app',
    iosBundleId: 'com.example.posNlh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhpnZDYQjaO_TrxErzZRJK3RkYEJrSJ0',
    appId: '1:216483381190:web:7102da0aa7d17e1a9a3cc7',
    messagingSenderId: '216483381190',
    projectId: 'pos-nlh',
    authDomain: 'pos-nlh.firebaseapp.com',
    storageBucket: 'pos-nlh.firebasestorage.app',
    measurementId: 'G-P89MNQ15N5',
  );
}
